// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2JGNC2ohBI2uHOjju64zixTd4YXy5qDc',
    appId: '1:950599949267:web:27940ef740c5088d44ed26',
    messagingSenderId: '950599949267',
    projectId: 'aundre-ceb64',
    authDomain: 'aundre-ceb64.firebaseapp.com',
    storageBucket: 'aundre-ceb64.appspot.com',
    measurementId: 'G-JST2MT1K2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFpNJ38LGLLhiAvNwtN55pCSL6o8-CZg',
    appId: '1:950599949267:android:d5219a9f97f48b1044ed26',
    messagingSenderId: '950599949267',
    projectId: 'aundre-ceb64',
    storageBucket: 'aundre-ceb64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChn8h7c563e09w6Yo3oLFrMYkUSHTjfCI',
    appId: '1:950599949267:ios:89cfe8c4bd78d23844ed26',
    messagingSenderId: '950599949267',
    projectId: 'aundre-ceb64',
    storageBucket: 'aundre-ceb64.appspot.com',
    iosClientId: '950599949267-7290ivg0htav75l37nfeo1rm4dco1kfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.audre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChn8h7c563e09w6Yo3oLFrMYkUSHTjfCI',
    appId: '1:950599949267:ios:7eaffffe412e7e2d44ed26',
    messagingSenderId: '950599949267',
    projectId: 'aundre-ceb64',
    storageBucket: 'aundre-ceb64.appspot.com',
    iosClientId: '950599949267-0k9r96s6hk1527ta77c1h040ugpoagim.apps.googleusercontent.com',
    iosBundleId: 'com.example.audre.RunnerTests',
  );
}
